import KeyMirror from 'key-mirror';

export default KeyMirror({
    GET_USERS_LOGIN_SUCCESS: null,
    GET_USERS_LOGIN_FAILURE: null,

    GET_REGISTER_SUCCESS:null,
    GET_REGISTER_FAILURE:null,

    GET_USER_MENU_SUCCESS: null,
    GET_USER_MENU_FAILURE: null,

    GET_ADMIN_MENU_SUCCESS:null,
    GET_ADMIN_MENU_FAILUER:null,

    CHANGE_PAGE_SUCCSEE:null,

    GET_ADMIN_SERVER_SUCCESS:null,
    GET_ADMIN_SERVER_FAILURE:null,

    GET_SERVER_ADD_SUCCESS:null,
    GET_SERVER_ADD_FAILURE:null,

    GET_SERVER_DELETE_SUCCESS:null,
    GET_SERVER_DELETE_FAILURE:null,

    GET_SERVER_UPDATA_SUCCESS:null,
    GET_SERVER_UPDATA__FAILURE:null,



})

